export const SET_SINGER = 'SET_SINGER'

export const SET_PLAY_STATE = 'SET_PLAY_STATE'

export const SET_FULLSCREEN = 'SET_FULLSCREEN'

export const SET_PLAYLIST = 'SET_PLAYLIST'

export const SET_SEQENCE_LIST = 'SET_SEQENCE_LIST'

export const SET_MODE = 'SET_MODE'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

